# Generated by Django 3.2 on 2022-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220209_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='ok', max_length=55, verbose_name='Category Slug'),
        ),
    ]
