# Generated by Django 4.0.2 on 2022-02-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='Color',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='Size',
            field=models.CharField(max_length=20, null=True, verbose_name='Size'),
        ),
    ]
