# Generated by Django 4.0.2 on 2022-02-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_attributes_color_alter_attributes_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.BigIntegerField(null=True),
        ),
    ]
