# Generated by Django 4.0.2 on 2022-02-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_product_is_active_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
