# Generated by Django 4.0.2 on 2022-02-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_product_is_active_remove_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
